# Generated by Django 5.1.7 on 2025-04-11 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0002_alter_queue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Service priority (lower numbers have higher priority)'),
        ),
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='queue_manager.queue')),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='queue_manager.window')),
            ],
            options={
                'verbose_name': 'Assignment Log',
                'verbose_name_plural': 'Assignment Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
