# Generated by Django 5.1.7 on 2025-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='priority',
            field=models.BooleanField(default=False, help_text='Check for high priority'),
        ),
    ]
