# Generated by Django 5.1.7 on 2025-04-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0003_service_priority_assignmentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='priority',
        ),
        migrations.DeleteModel(
            name='AssignmentLog',
        ),
    ]
